d18/d18/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path,include
from products.views import *
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',index, name = 'index'),
    path('products/', include('products.urls', namespace ='products')),
    path('users/', include('users.urls', namespace ='users')),
    path('admin/password_reset/', auth_views.PasswordResetView.as_view(),
         name = 'admin_password_reset'),
    path('admin/password_reset/done', auth_views.PasswordResetDoneView.as_view(),
         name = 'password_reset_done'),
    path('admin/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name = 'password_reset_confirm'),
    path('admin/reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name = 'password_reset_complete'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

d18/products/urls.py
from django.contrib import admin
from django.urls import path
from products.views import *
app_name = 'products'
urlpatterns = [
    path('',products, name = 'index'),
    path('baskets/add/<int:product_id>/', basket_add, name = 'basket_add'),
    path('baskets/remove/<int:product_id>/', basket_remove, name = 'basket_remove')

]

d18/users/urls.py
from django.urls import path

from .views import *

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name = 'register'),
    path('profile/', profile, name = 'profile'),
    path('logout/', logout, name = 'logout'),


]

d18/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
        image = models.ImageField(upload_to='users_image', null=True, blank=True)

d18/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm , UserChangeForm, forms
from .models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholer': 'Введите ник'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholer': 'Введите пароль'}))

    class Meta:
        model = User
        fields = ['username','password']

class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class' :'form-control py-4',
        'placeholer' :'Введеите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class' :'form-control py-4',
        'placeholer' :'Введите email'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4',
        'placeholer': 'Введите email'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholer': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholer': 'Повторите пароль'}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholer': 'Введите ник'}))

    class Meta:
        model = User
        fields = ['first_name','last_name','email','password1','password2','username']

class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control py-4'})),
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control py-4'})),
    image = forms.ImageField(widget=forms.FileInput(attrs={'class':'custom-file-input'}), required=False),
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4', 'readonly':True})),
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4', 'readonly':True}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image', 'username', 'email')

d18/users/views.py
from django.urls import reverse
from django.shortcuts import render,  HttpResponseRedirect
from products.models import Basket
from django.contrib import auth, messages
from .models import User
from .forms import UserLoginForm, UserRegistrationForm, UserProfileForm
app_name = 'users'

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username =  request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username = username, password = password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('index'))
    else:
        form = UserLoginForm()
    context = {
        'form':form,
    }
    return render(request, 'login.html', context=context)

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data = request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Вы успешно зарегистрировались!')
            return HttpResponseRedirect(reverse('users:login'))

    else:
        form = UserRegistrationForm()
    context = {'form': form,}
    return render(request, 'register.html', context=context)

def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
        else:print(form.errors)
    else:
        form = UserProfileForm(instance=request.user)
        baskets = Basket.objects.filter(user = request.user)
        total_sum = 0
        total_quantity = 0
        for i in baskets:
            total_sum += i.sum()
            total_quantity += i.quantity

        context = {'Title':'Профиль',
                   'form': form,
                   'baskets': baskets,
                   'total_sum': total_sum,
                   'total_quantity': total_quantity,}

    return render(request, 'profile.html', context=context)




def logout(request):
    auth.logout(request)
    return HttpResponseRedirect (reverse('index'))

d18/users/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Store - Авторизация</title>
    <link href="/static/vendor/css/auth.css" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">

    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="../vendor/js/auth-admin.js"></script>


</body>
</html>

d18/users/templates/baskets.html
{% if baskets %}
<h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
                Корзина <span class="badge badge-secondary badge-pill">{{total_quantity}}</span>
            </h4>
    {% for basket in baskets %}
<div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ basket.product.name }}</h5>
                    <p class="card-text">{{ basket.product.description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-lg-4">
                                <input name="basketID" type="number" class="form-control"
                                       value="1" min="0">
                            </div>
                            <div class="col-lg-4">{{ basket.sum }} руб.</div>
                            <div class="col-lg-4">
                                <a href="{% url 'products:basket_remove' basket.id %}">
                                    delete
                                </a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
   {% endfor %}
<div class="card mb-3">
                <div class="card-footer">
                    <p class="float-left">Итого</p>
                    <h4 class="float-right">{{ total_sum }} руб.</h4>
                </div>
            </div>
<a class="btn btn-success btn-lg float-right" href="">
                Оформить заказ
            </a>
{% else %}
<h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
                Корзина пуста <span class="badge badge-secondary badge-pill">3</span>
            </h4>
{% endif %}

d18/users/templates/email_verification.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Store - Подтверждение электронной почты</title>
    <link href="../vendor/css/auth.css" rel="stylesheet"/>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Поздравляем</h3>
                            </div>
                            <div class="card-body text-center">
                                <h4>Ваша учетная запись успешно подтверждена!</h4>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="register.html">Продолжить</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
</body>
</html>

d18/users/templates/login.html
{% extends 'base.html' %}

    {% block css %}
    <link href="/static/vendor/css/auth.css" rel="stylesheet">
    {% endblock %}

{% block content %}
<main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        {% if from.non_filed_errors %}
                        <div class="alert
                         {% if messages %} alert-success
                         {% else %} alert-warning
                         {% endif %}
                         alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {% if messages %}
                                 {% for message in messages %}
                                     {{message}}
                                 {% endfor %}
                            {% else %}
                                 {{form.non_filed_errors}}
                            {% endif %}
                            <strong>Holy guacamole!</strong> You should check in on some of those fields below.
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                            </div>
                            <div class="card-body">
                                <form action = "{% url 'users:login' %}" method = "post">
                                    {% csrf_token %}
                                    {{form.as_p}}
<!--                                    <div class="form-group">-->
<!--                                        <label class="small mb-1" for="inputEmailAddress">Имя пользователя</label>-->
<!--                                        <input class="form-control py-4" id="inputEmailAddress" type="text"-->
<!--                                               placeholder="Введите имя пользователя"/>-->
<!--                                    </div>-->
<!--                                    <div class="form-group">-->
<!--                                        <label class="small mb-1" for="inputPassword">Пароль</label>-->
<!--                                        <input class="form-control py-4" id="inputPassword" type="password"-->
<!--                                               placeholder="Введите пароль"/>-->
<!--                            </div>-->
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a class="small" href="{% url 'admin_password_reset'%}">Забыли пароль?</a>
                                        <input class="btn btn-primary" type="submit" value="Авторизоваться">
                                    </div>
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a href="#">
                                            <i class="fab fa-google fa-2x" style="color: #d9503e;"></i>
                                        </a>
                                        <a href="#">
                                            <i class="fab fa-vk fa-2x" style="color: #4a658b;"></i>
                                        </a>
                                        <a href="#">
                                            <i class="fab fa-github fa-2x" style="color: #303030;"></i>
                                        </a>
                                        <a href="#">
                                            <i class="fab fa-facebook fa-2x" style="color: #405794;"></i>
                                        </a>
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'users:register'%}">Нужен аккаунт? Зарегистрируйся!</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
{% endblock %}

d18/users/templates/profile.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    <link href="/static/vendor/css/profile.css" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-7">
            <h4 class="mt-3 mb-3">Профиль</h4>
                <div class="col-lg-12 text-center">
                    <img width="100" height="100"
                         src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'vendor/img/users/default_avatar.jpg' %} {% endif %}"
                         class="img-thumbnail">
                </div>
            <form action="{% url 'users:profile'%}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                            {{ form.first_name}}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                            {{ form.last_name}}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            {{ form.image}}
                            <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите изображение</label>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                        {{ form.username}}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной почты</label>
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-5">
            {% include 'baskets.html' %}

    </div>
</div>
{% endblock %}

d18/users/templates/register.html
{% extends 'base.html' %}

{% block css %}
    <link href="/static/vendor/css/auth.css" rel="stylesheet">
    {% endblock %}

{% block content %}
<main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-7">
                        {% if form.errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {{form.errors}}
                            <strong>Holy guacamole!</strong> You should check in on some of those fields below.
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'users:register' %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{form.first_name.id_for_label}}">Имя</label>
                                                {{form.first_name}}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{form.last_name.id_for_label}}">Фамилия</label>
                                                {{form.last_name}}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <label class="small mb-1" for={{form.username.id_for_label}}>Имя пользователя</label>
                                            {{form.username}}
                                        </div>
                                        <div class="col-md-6">
                                            <label class="small mb-1" for={{form.email.id_for_label}}>Адрес электронной
                                                почты</label>
                                            {{form.email}}
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for={{form.password1.id_for_label}}>Пароль</label>
                                                {{form.password1}}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for={{form.password2.id_for_label}}>Подтверждение
                                                    пароля</label>
                                                {{form.password2}}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group mt-4 mb-0">
                                        <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="login.html">Уже есть аккаунт? Авторизоваться</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
{% endblock %}